name: king_tracker_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.5.0+8

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  pdf: ^3.11.1
  printing: ^5.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/stephen_king_books.json
    - assets/data/stephen_king_adaptations.json
    - assets/images/App_background_2.png
    - assets/images/app_background_7.png
    - assets/images/app_background_light_4.png
    - assets/images/app_background_light_7.png
